<HomeScreen>:
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 20

        Label:
            text: "Welcome to Exercise App"
            font_size: 32

        Button:
            text: "Browse Exercises"
            font_size: 24
            size_hint_y: None
            height: "50dp"
            on_press: app.root.current = "exercise_list"

        Button:
            text: "Create Workout"
            font_size: 24
            size_hint_y: None
            height: "50dp"
            on_press: app.root.current = "build_workout"

        Button:
            text: "Create Program"
            font_size: 24
            size_hint_y: None
            height: "50dp"
           

        Button:
            text: "Start Timer"
            font_size: 24
            size_hint_y: None
            height: "50dp"
