<HomeScreen>:
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 20

        Label:
            text: "Welcome to Exercise App"
            font_size: 32

        Button:
            text: "Browse Exercises"
            font_size: 24
            size_hint_y: None
            height: "50dp"

        Button:
            text: "Create Workout Program"
            font_size: 24
            size_hint_y: None
            height: "50dp"

        Button:
            text: "Start Timer"
            font_size: 24
            size_hint_y: None
            height: "50dp"
